/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({
  'x' : IDL.Int,
  'y' : IDL.Int,
  'z' : IDL.Int,
});
export const BlockType = IDL.Variant({
  'LOG' : IDL.Null,
  'STAIR' : IDL.Null,
  'STONE' : IDL.Null,
  'GLASS' : IDL.Null,
  'GRASS' : IDL.Null,
  'COBBLESTONE' : IDL.Null,
  'CLAY' : IDL.Null,
  'COAL' : IDL.Null,
  'DIRT' : IDL.Null,
  'BRICK' : IDL.Null,
  'SAND' : IDL.Null,
  'SLAB' : IDL.Null,
  'WOOD' : IDL.Null,
  'LEAVES' : IDL.Null,
  'FENCE' : IDL.Null,
  'BEDROCK' : IDL.Null,
  'PLANKS' : IDL.Null,
});
export const Block = IDL.Record({
  'blockType' : BlockType,
  'texture' : IDL.Text,
  'position' : Position,
});
export const InventoryView = IDL.Record({
  'items' : IDL.Vec(IDL.Tuple(BlockType, IDL.Nat)),
});
export const WorldView = IDL.Record({ 'blocks' : IDL.Vec(Block) });
export const PlayerView = IDL.Record({
  'principal' : IDL.Principal,
  'currentWorld' : WorldView,
  'inventory' : InventoryView,
});

export const idlService = IDL.Service({
  'findBlock' : IDL.Func(
      [IDL.Principal, Position],
      [IDL.Opt(Block)],
      ['query'],
    ),
  'getInventory' : IDL.Func([IDL.Principal], [InventoryView], ['query']),
  'getPlayer' : IDL.Func([IDL.Principal], [PlayerView], []),
  'getWorldBlocks' : IDL.Func([IDL.Principal], [IDL.Opt(WorldView)], ['query']),
  'updateBlock' : IDL.Func([IDL.Principal, Block], [Block], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({ 'x' : IDL.Int, 'y' : IDL.Int, 'z' : IDL.Int });
  const BlockType = IDL.Variant({
    'LOG' : IDL.Null,
    'STAIR' : IDL.Null,
    'STONE' : IDL.Null,
    'GLASS' : IDL.Null,
    'GRASS' : IDL.Null,
    'COBBLESTONE' : IDL.Null,
    'CLAY' : IDL.Null,
    'COAL' : IDL.Null,
    'DIRT' : IDL.Null,
    'BRICK' : IDL.Null,
    'SAND' : IDL.Null,
    'SLAB' : IDL.Null,
    'WOOD' : IDL.Null,
    'LEAVES' : IDL.Null,
    'FENCE' : IDL.Null,
    'BEDROCK' : IDL.Null,
    'PLANKS' : IDL.Null,
  });
  const Block = IDL.Record({
    'blockType' : BlockType,
    'texture' : IDL.Text,
    'position' : Position,
  });
  const InventoryView = IDL.Record({
    'items' : IDL.Vec(IDL.Tuple(BlockType, IDL.Nat)),
  });
  const WorldView = IDL.Record({ 'blocks' : IDL.Vec(Block) });
  const PlayerView = IDL.Record({
    'principal' : IDL.Principal,
    'currentWorld' : WorldView,
    'inventory' : InventoryView,
  });
  
  return IDL.Service({
    'findBlock' : IDL.Func(
        [IDL.Principal, Position],
        [IDL.Opt(Block)],
        ['query'],
      ),
    'getInventory' : IDL.Func([IDL.Principal], [InventoryView], ['query']),
    'getPlayer' : IDL.Func([IDL.Principal], [PlayerView], []),
    'getWorldBlocks' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorldView)],
        ['query'],
      ),
    'updateBlock' : IDL.Func([IDL.Principal, Block], [Block], []),
  });
};

export const init = ({ IDL }) => { return []; };