/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Block {
  'blockType' : BlockType,
  'texture' : string,
  'position' : Position,
}
export type BlockType = { 'LOG' : null } |
  { 'STAIR' : null } |
  { 'STONE' : null } |
  { 'GLASS' : null } |
  { 'GRASS' : null } |
  { 'COBBLESTONE' : null } |
  { 'CLAY' : null } |
  { 'COAL' : null } |
  { 'DIRT' : null } |
  { 'BRICK' : null } |
  { 'SAND' : null } |
  { 'SLAB' : null } |
  { 'WOOD' : null } |
  { 'LEAVES' : null } |
  { 'FENCE' : null } |
  { 'BEDROCK' : null } |
  { 'PLANKS' : null };
export interface InventoryView { 'items' : Array<[BlockType, bigint]> }
export interface PlayerView {
  'principal' : Principal,
  'currentWorld' : WorldView,
  'inventory' : InventoryView,
}
export interface Position { 'x' : bigint, 'y' : bigint, 'z' : bigint }
export interface WorldView { 'blocks' : Array<Block> }
export interface _SERVICE {
  'findBlock' : ActorMethod<[Principal, Position], [] | [Block]>,
  'getInventory' : ActorMethod<[Principal], InventoryView>,
  'getPlayer' : ActorMethod<[Principal], PlayerView>,
  'getWorldBlocks' : ActorMethod<[Principal], [] | [WorldView]>,
  'updateBlock' : ActorMethod<[Principal, Block], Block>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];