/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorldView {
    blocks: Array<Block>;
}
export interface PlayerView {
    principal: Principal;
    currentWorld: WorldView;
    inventory: InventoryView;
}
export interface Position {
    x: bigint;
    y: bigint;
    z: bigint;
}
export interface InventoryView {
    items: Array<[BlockType, bigint]>;
}
export interface Block {
    blockType: BlockType;
    texture: string;
    position: Position;
}
export enum BlockType {
    LOG = "LOG",
    STAIR = "STAIR",
    STONE = "STONE",
    GLASS = "GLASS",
    GRASS = "GRASS",
    COBBLESTONE = "COBBLESTONE",
    CLAY = "CLAY",
    COAL = "COAL",
    DIRT = "DIRT",
    BRICK = "BRICK",
    SAND = "SAND",
    SLAB = "SLAB",
    WOOD = "WOOD",
    LEAVES = "LEAVES",
    FENCE = "FENCE",
    BEDROCK = "BEDROCK",
    PLANKS = "PLANKS"
}
export interface backendInterface {
    findBlock(principal: Principal, position: Position): Promise<Block | null>;
    getInventory(principal: Principal): Promise<InventoryView>;
    getPlayer(principal: Principal): Promise<PlayerView>;
    getWorldBlocks(principal: Principal): Promise<WorldView | null>;
    updateBlock(principal: Principal, block: Block): Promise<Block>;
}
import type { Block as _Block, BlockType as _BlockType, InventoryView as _InventoryView, PlayerView as _PlayerView, Position as _Position, WorldView as _WorldView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async findBlock(arg0: Principal, arg1: Position): Promise<Block | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findBlock(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findBlock(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(arg0: Principal): Promise<InventoryView> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory(arg0);
                return from_candid_InventoryView_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory(arg0);
            return from_candid_InventoryView_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: Principal): Promise<PlayerView> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_PlayerView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_PlayerView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorldBlocks(arg0: Principal): Promise<WorldView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorldBlocks(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorldBlocks(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlock(arg0: Principal, arg1: Block): Promise<Block> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlock(arg0, to_candid_Block_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Block_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlock(arg0, to_candid_Block_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Block_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BlockType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlockType): BlockType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Block_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Block): Block {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryView): InventoryView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerView): PlayerView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WorldView_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorldView): WorldView {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Block]): Block | null {
    return value.length === 0 ? null : from_candid_Block_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorldView]): WorldView | null {
    return value.length === 0 ? null : from_candid_WorldView_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    currentWorld: _WorldView;
    inventory: _InventoryView;
}): {
    principal: Principal;
    currentWorld: WorldView;
    inventory: InventoryView;
} {
    return {
        principal: value.principal,
        currentWorld: from_candid_WorldView_n12(_uploadFile, _downloadFile, value.currentWorld),
        inventory: from_candid_InventoryView_n6(_uploadFile, _downloadFile, value.inventory)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blocks: Array<_Block>;
}): {
    blocks: Array<Block>;
} {
    return {
        blocks: from_candid_vec_n14(_uploadFile, _downloadFile, value.blocks)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blockType: _BlockType;
    texture: string;
    position: _Position;
}): {
    blockType: BlockType;
    texture: string;
    position: Position;
} {
    return {
        blockType: from_candid_BlockType_n4(_uploadFile, _downloadFile, value.blockType),
        texture: value.texture,
        position: value.position
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<[_BlockType, bigint]>;
}): {
    items: Array<[BlockType, bigint]>;
} {
    return {
        items: from_candid_vec_n8(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BlockType, bigint]): [BlockType, bigint] {
    return [
        from_candid_BlockType_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LOG: null;
} | {
    STAIR: null;
} | {
    STONE: null;
} | {
    GLASS: null;
} | {
    GRASS: null;
} | {
    COBBLESTONE: null;
} | {
    CLAY: null;
} | {
    COAL: null;
} | {
    DIRT: null;
} | {
    BRICK: null;
} | {
    SAND: null;
} | {
    SLAB: null;
} | {
    WOOD: null;
} | {
    LEAVES: null;
} | {
    FENCE: null;
} | {
    BEDROCK: null;
} | {
    PLANKS: null;
}): BlockType {
    return "LOG" in value ? BlockType.LOG : "STAIR" in value ? BlockType.STAIR : "STONE" in value ? BlockType.STONE : "GLASS" in value ? BlockType.GLASS : "GRASS" in value ? BlockType.GRASS : "COBBLESTONE" in value ? BlockType.COBBLESTONE : "CLAY" in value ? BlockType.CLAY : "COAL" in value ? BlockType.COAL : "DIRT" in value ? BlockType.DIRT : "BRICK" in value ? BlockType.BRICK : "SAND" in value ? BlockType.SAND : "SLAB" in value ? BlockType.SLAB : "WOOD" in value ? BlockType.WOOD : "LEAVES" in value ? BlockType.LEAVES : "FENCE" in value ? BlockType.FENCE : "BEDROCK" in value ? BlockType.BEDROCK : "PLANKS" in value ? BlockType.PLANKS : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Block>): Array<Block> {
    return value.map((x)=>from_candid_Block_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BlockType, bigint]>): Array<[BlockType, bigint]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BlockType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): _BlockType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Block_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Block): _Block {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blockType: BlockType;
    texture: string;
    position: Position;
}): {
    blockType: _BlockType;
    texture: string;
    position: _Position;
} {
    return {
        blockType: to_candid_BlockType_n18(_uploadFile, _downloadFile, value.blockType),
        texture: value.texture,
        position: value.position
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): {
    LOG: null;
} | {
    STAIR: null;
} | {
    STONE: null;
} | {
    GLASS: null;
} | {
    GRASS: null;
} | {
    COBBLESTONE: null;
} | {
    CLAY: null;
} | {
    COAL: null;
} | {
    DIRT: null;
} | {
    BRICK: null;
} | {
    SAND: null;
} | {
    SLAB: null;
} | {
    WOOD: null;
} | {
    LEAVES: null;
} | {
    FENCE: null;
} | {
    BEDROCK: null;
} | {
    PLANKS: null;
} {
    return value == BlockType.LOG ? {
        LOG: null
    } : value == BlockType.STAIR ? {
        STAIR: null
    } : value == BlockType.STONE ? {
        STONE: null
    } : value == BlockType.GLASS ? {
        GLASS: null
    } : value == BlockType.GRASS ? {
        GRASS: null
    } : value == BlockType.COBBLESTONE ? {
        COBBLESTONE: null
    } : value == BlockType.CLAY ? {
        CLAY: null
    } : value == BlockType.COAL ? {
        COAL: null
    } : value == BlockType.DIRT ? {
        DIRT: null
    } : value == BlockType.BRICK ? {
        BRICK: null
    } : value == BlockType.SAND ? {
        SAND: null
    } : value == BlockType.SLAB ? {
        SLAB: null
    } : value == BlockType.WOOD ? {
        WOOD: null
    } : value == BlockType.LEAVES ? {
        LEAVES: null
    } : value == BlockType.FENCE ? {
        FENCE: null
    } : value == BlockType.BEDROCK ? {
        BEDROCK: null
    } : value == BlockType.PLANKS ? {
        PLANKS: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
